replicaCount: 2
resources:
  requests:
    cpu: 100m
    memory: 50Mi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: {{ cookiecutter.name|lower|replace('-', '.')  }}
    paths:
    - '/'
  - host: www.{{ cookiecutter.name|lower|replace('-', '.')  }}
    paths:
    - '/'
  tls:
  - secretName: {{ cookiecutter.name }}
    hosts:
    - {{ cookiecutter.name|lower|replace('-', '.')  }}
    - www.{{ cookiecutter.name|lower|replace('-', '.')  }}
